version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app
    overwrite: yes

permissions:
  - object: /home/ec2-user/app
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
  - object: /home/ec2-user/app
    owner: ec2-user
    group: ec2-user
    pattern: "**"
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: scripts/start.sh
      timeout: 120
      runas: ec2-user
